### ISSUE TITLE
String literal as object property name fails (TypeError: base[type] is not a function)

### ISSUE THREAD

**Issue by VladimirShugaev** [treycordova/nativejsx#25]
version 4.2.0 fails to process files with string literal as object property name

Create a test.js file with content:
```javascript
const test = {
  ok: null,
  'no-ok': null,
};

Try processing it
```
`nativejsx test.js --output ./here`

Results in error:
```
nativejsx/node_modules/acorn/dist/walk.js:29
    base[type](node, st, c)
              ^

TypeError: base[type] is not a function
...
```

My short investigation showed it is most probably caused by https://github.com/treycordova/nativejsx/commit/52770907fb942fdfa94887283e3d6a7b0066f8e1

**Comment by j3l11234** [comment]
I have fixed this bug, and create a pull request. #24 
you can use my fork temporarily.
```
npm install https://github.com/j3l11234/nativejsx/archive/4.2.0.2.tar.gz --save-dev
```

**Comment by hooriza** [comment]
@treycordova 
I have the same problem.
The [PR related](#24) to this has already been merged, so would you please release it?

**Comment by treycordova** [comment]
This is released as 4.3.0! Sorry for the delay.
